apiVersion: apps/v1
kind: Deployment
metadata:
  name: mykubernetes-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: mykubernetesapp
          image: mykubernetesapp:latest
          imagePullPolicy: IfNotPresent